schema_version = "1.0.0"
id = "autodesk_3ds_format"
name = "Autodesk 3DS format"
version = "2.5.1"
tagline = "3DS Import/Export meshes, UVs, materials, textures, cameras . . "
maintainer = "Community"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/io_scene_3ds"
copyright = ["2024 Bob Holcomb", "2024 Campbell Barton", "2024 Sebastian Schrand"]
